ci: only running by node

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,12 +2,41 @@ name: CI
 
 on:
   pull_request:
-    branches:
-      - main
 
 jobs:
-  lint:
+  setup:
     runs-on: ubuntu-latest
+    outputs:
+      changed_files_node_all: ${{ steps.changed_files.outputs.node_all_any_changed }}
+      changed_files_node_lint: ${{ steps.changed_files.outputs.node_lint_any_changed }}
+      changed_files_renovate: ${{ steps.changed_files.outputs.renovate_any_changed }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Get all test, doc and src files that have changed
+        id: changed_files
+        uses: tj-actions/changed-files@v44
+        with:
+          files_yaml: |
+            node_all:
+              - tsconfig.json
+              - package.json
+              - package-lock.json
+              - .tool-versions
+              - src/**
+            node_lint:
+              - biome.json
+            renovate:
+              - renovate.json5
+
+      - name: Display changed files
+        run: |
+          echo '${{ toJson(steps.changed_files.outputs) }}'
+        
+  node_lint:
+    runs-on: ubuntu-latest
+    needs: setup
+    if: needs.setup.outputs.changed_files_node_all == 'true' || needs.setup.outputs.changed_files_node_lint == 'true'
     steps:
       - uses: actions/checkout@v4
 
@@ -21,8 +50,10 @@ jobs:
       - name: Run lint
         run: npm run lint
 
-  test:
+  node_test:
     runs-on: ubuntu-latest
+    needs: setup
+    if: needs.setup.outputs.changed_files_node_all == 'true'
     steps:
       - uses: actions/checkout@v4
 
@@ -42,10 +73,10 @@ jobs:
           directory: ./coverage/ # optional
           fail_ci_if_error: true # optional2 (default = false)
 
-  pack:
-    needs:
-      - test
+  node_pack:
     runs-on: ubuntu-latest
+    needs: setup
+    if: needs.setup.outputs.changed_files_node_all == 'true'
     steps:
       - uses: actions/checkout@v4
 
@@ -61,3 +92,29 @@ jobs:
 
       - name: Run pack
         run: npm pack
+
+  renovate:
+    runs-on: ubuntu-latest
+    needs: setup
+    if: needs.setup.outputs.changed_files_renovate == 'true'
+    steps:
+      - uses: actions/checkout@v4
+
+      - run: |
+          npx --package renovate -c 'renovate-config-validator'
+
+  required_jobs:
+    runs-on: ubuntu-latest
+    needs:
+      - node_lint
+      - node_test
+      - node_pack
+      - renovate
+    if: always()
+    steps:
+      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "Some required jobs failed or cancelled."
+          exit 1
+
+      - run: echo "All required jobs passed."
